myapp/urls.py
from django.conf.urls import url

from myapp import views

urlpatterns = [
    url(r'^$',views.mainweb,name='mainweb'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$',views.register,name='register'),
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^uploadimg/$',views.uploadimg,name='uploadimg'),
    url(r'^goodsinfo/(\d+)/$',views.goodsinfo,name='goodsinfo'),
    url(r'^verifycode/\d+/$',views.verifycode,name='verifycode'),
    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^subcart/$', views.subcart, name='subcart'),
    url(r'^order/(\d+)/$', views.order, name='order'),
    url(r'^changecartstatus/$', views.changecartstatus, name='changecartstatus'),  # 修改选中状态
    url(r'^changecartselect/$', views.changecartselect, name='changecartselect'),  # 全选/取消全选
    url(r'^delallgoods/$', views.delallgoods, name='delallgoods'),  # 清空购物车
    url(r'^delselectgoods/$', views.delselectgoods, name='delselectgoods'),  # 删除选中商品
    url(r'^delbut/(\d+)/$', views.delbut, name='delbut'),  # 删除按钮删除对应商品
    url(r'^dynflashnum/$', views.dynflashnum, name='dynflashnum'),  # 删除按钮删除对应商品
    url(r'^checkaccount/$', views.checkaccount, name='checkaccount'),  # 删除按钮删除对应商品
    url(r'^generateorder/$', views.generateorder, name='generateorder'),  # 下单
    url(r'^notify/$', views.notify, name='notify'),  # 订单支付后，支付宝给客户端的提示url
    url(r'^returnurl/$', views.returnurl, name='returnurl'),  # 订单支付后，支付宝给客户端的提示url
    url(r'^pay/$', views.pay, name='pay'),

]

paixienet/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('myapp.urls',namespace='paixienet')),
]

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎登录</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/layout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <script src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/user.js' %}"></script>



</head>

<body>


    <div class="login-header">
        <a href="#" class="logo"></a>
        <h1>欢迎登录</h1>
    </div>
    <div class="login-content">
        <div class="login-area">
            <a href="#" class="ad">
                <img src="{% static 'images/login-ad.jpg' %}" alt="">
            </a>
            <div class="form">
                <form action="{% url 'paixienet:login' %}" method="post">
                    {% csrf_token %}
                <p>
                    <strong>登录拍鞋平台</strong>
                    <a href="{% url 'paixienet:register' %}">免费注册</a>
                    <span>还没有拍鞋网帐号？</span>
                </p>



                <div class="base-text username">
                    <i></i>
                    <input class="login-text" type="text" placeholder="手机号/邮箱" name="account"/>
                </div>
                <div class="v-ok">&nbsp;</div>
                <div class="base-text password">
                    <i></i>
                    <input class="login-text" type="password" placeholder="请输入密码" name="password"/>
                </div>
                <div class="v-ok">&nbsp;</div>
                <div class="auto-login">
                    <label for="">
                        <input type="checkbox"/>
                        下次自动登录
                    </label>
                    <a href="#">忘记密码?</a>
{#                    <a class="orange-button" href="javascript:;">登 录</a>#}
                    <a><input type="submit" class="orange-button"  value="登 录" id="input"></a>
                </div>
                <div class="other-login">
                    你也可以使用以下帐号登录
                    <p>
                        <a class="qq" href="#"></a>
                        <a class="alipay" href="#"></a>
                        <a class="sina" href="#"></a>
                        <a class="renren" href="#"></a>
                        <a class="wangyi" href="#"></a>
                        <a class="xunlei" href="#"></a>
                        <a class="baidu" href="#"></a>
                        <a class="qh360" href="#"></a>
                        <a class="wechat" href="#"></a>
                        <a class="wanlitong" href="#"></a>
                    </p>
                </div>
                </form>
            </div>
            <div class="wechatbox">
                <h2>用拍鞋网APP 扫码安全登录</h2>
                <img src="{% static 'images/qrcodelogin.png' %}" alt="">
                <p>
                    <a href="#">刷新二维码</a>
                    |
                    <a href="#">
                        使用帮助
                        <span>
                            <i></i>
                            扫描不上，版本过低？
                        </span>
                    </a>
                </p>
            </div>
            <div class="way">
                <a href="javascript:;"></a>
            </div>
        </div>
    </div>
    <div class="login-footer">
        Copyright © 2007-2016 Paixie.net All Rights Reserved 增值电信业务经营许可证：闽B2-20110084
    </div>
</body>
</html>

templates/register.html
{% load  static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎注册</title>


    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.css' %}">


    <link rel="stylesheet" type="text/css" href="{% static 'css/layout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
    <script src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
    <script src="{% static 'js/verifycode.js' %}"></script>


</head>
<body>
<div class="login-header">
    <a href="#" class="logo"></a>
    <h1>欢迎注册</h1>
</div>
<div class="login-content">
    <div class="register-area">


        {# 注册区域//////////////////////////////////////////////////////////////////////// #}

        <div class="form">
            <form action="{% url 'paixienet:register' %}" method="post" id="formid">
                {% csrf_token %}
                <div class="register-area-left">
                    <div class="form-group has-success has-feedback" id="account">
                        <label class="control-label col-sm-3" for="inputSuccessAccount">账&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号:</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="inputSuccessAccount"
                                   name="account" required="required">
                            <span class="glyphicon glyphicon-ok form-control-feedback" ></span>
                        </div>
                        <i></i>
                    </div>
                    <div class="form-group has-success has-feedback" id="password">
                        <label class="control-label col-sm-3" for="password">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码:</label>
                        <div class="col-sm-9">
                            <input type="password" class="form-control" id="password"
                                   name="password" required="required">
                            <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
                        </div>
                        <i></i>
                    </div>
                    <div class="form-group has-success has-feedback" id="passwd">
                        <label class="control-label col-sm-3" for="passwd">确认密码:</label>
                        <div class="col-sm-9">
                            <input type="password" class="form-control" id="passwd"
                                   name="passwd" required="required">
                            <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
                        </div>
                        <i></i>
                    </div>
                    <div class="form-group has-success has-feedback" id="nickname">
                        <label class="control-label col-sm-3" for="inputSuccessNickname">昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称:</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="inputSuccessNickname"
                                   name="nickname" required="required">
                            <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>

                        </div>
                        <i></i>
                    </div>
                    <div>
                        <div class="form-group has-success has-feedback verifycode" id="codearea">
                            {# inputSuccess3 可改变宽度 #}
                            <label class="control-label col-sm-3 verifycode-label" for="verifycode1">验&nbsp;&nbsp;证&nbsp;&nbsp;码:</label>
                            <div class="col-sm-9 input-code verifycode-input">
                                <input type="text" class="form-control inputSuccess3-code" id="verifycode1"
                                       name="verifycode" required="required">
                                <span><img src="{% url 'paixienet:verifycode' %}" id='verifycode'></span>
                                <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="false"></span>

                            </div>

                        </div>

                    </div>


                    <div class="agreement">
                        <lable>
                            <input type="checkbox" checked/>
                            我已阅读并同意
                            <a href="#">《拍鞋服务协议》</a>
                        </lable>
                    </div>


                    <input type="button" value="立即注册" class="blue-button">

                </div>
                <div class="register-area-right">

                </div>

            </form>
        </div>

        {# 注册区域//////////////////////////////////////////////////////////////////////// #}


        <div class="side">
            我已有拍鞋网账户
            <br>
            现在就
            <a href="{% url 'paixienet:login' %}">立即登录</a>
        </div>
    </div>
</div>
<div class="login-footer">
    Copyright © 2007-2016 Paixie.net All Rights Reserved 增值电信业务经营许可证：闽B2-20110084
</div>
</body>
</html>

templates/uploadimg.html
{% load  static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>拍鞋网</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/layout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cart.css' %}">
    <script src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/cart.js' %}"></script>




</head>

<body>


<div class="head" id="head">
<div class="head-topline">
    <div class="head-topLogin">
        <div class="head_topLoginright">
                    <span class="login-cart">
                        <a href="{% url 'paixienet:cart' %}"><i></i>购物车<b>0</b></a>
                        <div class="cartshow">
                            <b class="cartboth">您还没有购买任何商品，快去挑选把！</b>
                        </div>
                    </span>
            <span class="login-icon">|</span>
                    <span class="login-paixie">
                        <a href="#">我的拍鞋<i></i></a>
                        <ul>
                            <li>
                                <a href="#">我的订单</a></li>
                            <li>
                                <a href="#">我的收藏</a></li>
                            <li>
                                <a href="#">我的优惠券</a></li>
                        </ul>
                    </span>
            <span class="login-icon">|</span>
            <span class="login-message"><a href="#">消息</a></span>
            <span class="login-icon">|</span>
            <span class="login-zone"><a href="#">会员俱乐部</a></span>
            <span class="login-icon">|</span>
                    <span class="login-paixie">
                        <a href="#">网站导航<i></i></a>
                        <ul>
                            <li>
                                <a href="#">商家入驻</a>
                            </li>
                            <li>
                                <a href="#">了解拍鞋网</a>
                            </li>
                            <li>
                                <a href="#">网站地图</a>
                            </li>
                            <li>
                                <a href="#">新手帮助</a>
                            </li>
                        </ul>
                    </span>
        </div>
        <div class="head_topLoginleft">
            <a href="#" class="mbicon"></a>
            <p class="loginOut">
                <span>您好，欢迎来拍鞋网！</span>
                <a href="{% url 'paixienet:login' %}" class="dologinBtn"></a> {# 登录 #}
                <span><a href="{% url 'paixienet:register' %}">免费注册</a></span>
            </p>
        </div>
    </div>
</div>
<form action="/uploadimg/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name = 'headimg'>
    <input type="submit" value="上传">
</form>
</div>


<div id="foot">
    <div class="foot-fiveicon">
        <ul class="foot-fiveicon-ul">
            <li style="width:250px;">
                <i class="authentic"></i>
                <a href="#">正品保证 假一赔十</a>
            </li>
            <li style="width:244px;">
                <i class="topay"></i>
                <a href="#">货到付款 全国范围</a>
            </li>
            <li style="width:253px;">
                <i class="hedging"></i>
                <a href="#">10天保值 差价返还</a>
            </li>
            <li style="width:215px;">
                <i class="postal"></i>
                <a href="#">满129元包邮</a>
            </li>
            <li>
                <i class="exchange"></i>
                <a href="#">15天无理由 免邮退换货</a>
            </li>
        </ul>
    </div>
    <div class="foot-nav">
        <ul>
            <li class="f-help">
                <b>新手帮助</b>
                <a href="#">注册会员</a>
                <a href="#">如何购物</a>
                <a href="#">拍鞋币说明</a>
                <a href="#">优惠券说明</a>
            </li>
            <li class="f-pay">
                <b>支付方式</b>
                <a href="#">支付宝快捷支付</a>
                <a href="#">网上银行支付</a>
                <a href="#">货到付款</a>
                <a href="#">运费说明</a>
            </li>
            <li class="f-service">
                <b>售后服务</b>
                <a href="#">退换货政策说明</a>
                <a href="#">退款详细说明</a>
                <a href="#">如何办理退换货</a>
            </li>
            <li class="f-about">
                <b>关于拍鞋网</b>
                <a href="#">了解拍鞋网</a>
                <a href="#">商家入驻</a>
                <a href="#">联系我们</a>
                <a href="#">拍鞋招聘</a>
            </li>
            <li class="f-contact">
                <b>客服中心</b>
                <a href="#">客服电话：4008 81 82 83</a>
                <a href="#">售后专线：0595-83092222</a>
                <a href="#">服务时间：周一到周日8:00-23:30</a>
            </li>
            <li class="f-app">
                <b>拍鞋网客户端</b>
                <p>随时随地上拍鞋！</p>
                <span class="mcode"></span>
            </li>
            <li class="f-wechat">
                <b>拍鞋微信</b>
                <p>查订单更快捷</p>
                <span class="pcode"></span>
                <a href="#" class="s-sina"></a>
                <a href="#" class="s-zone"></a>
            </li>
        </ul>
    </div>
    <div class="foot-copyright">
        <span>Copyright © 2007-2016 Paixie.net All Rights Reserved 闽B2-20110084</span>
    </div>
    <div class="foot-linktext">
        <i class="dolinkshow" id="dolinkshow"></i>
        <b>友情链接:</b>
        <a href="#">返利网</a>
        <a href="#">代购</a>
        <a href="#">穿衣搭配网</a>
        <a href="#">雅虎日本</a>
        <a href="#">江西老表网</a>
        <a href="#">石家庄招聘</a>
        <a href="#">海淘攻略</a>
        <a href="#">日本代购</a>
        <a href="#">钻戒</a>
        <a href="#">给惠网</a>
        <a href="#">258企业服务平台</a>
        <a href="#">拍鞋百科</a>
        <a href="#">手机靓号网</a>
        <a href="#">B2B电子商务</a>
        <a href="#">伊宅购村安商城</a>
        <a href="#">华为商城</a>
        <a href="#">万表网官网</a>
        <a href="#">装修</a>
        <a href="#">9.9包邮</a>
        <a href="#">手表品牌大</a>
        <a href="#">衣联网</a>
        <a href="#">中国丽人网</a>
    </div>
    <div class="foot-linkimg">
        <a href="#" class="investment"></a>
        <a href="#" class="ecommerce"></a>
        <a href="#" class="alipay"></a>
        <a href="#" class="scouring"></a>
        <a href="#" class="honesty"></a>
        <a href="#" class="commerce"></a>
        <a href="#" class="report"></a>
    </div>
</div>



</body>
</html>